// 设置搜索索引（对齐 Android SettingsSearchIndex）：分区 + 设置项标题 / 描述的文案键。
// 折叠分组没展开时内容不在 DOM 里，所以不能靠 DOM 现建索引；
// scripts/test-settings-search.mjs 会核对模板里的设置项都收录在这里
export interface SettingsSearchEntry {
  section: string
  title: string
  desc?: string
  /** 额外检索词（同义词、平台名），不显示 */
  keywords?: string[]
  macOnly?: boolean
}

export const SETTINGS_SEARCH_INDEX: SettingsSearchEntry[] = [
  { section: 'accounts', title: 'settings.accounts', desc: 'settings.accounts_desc', keywords: ['NetEase', '网易云', 'Bilibili', 'B站', '哔哩哔哩', 'YouTube', 'login', '登录'] },
  { section: 'general', title: 'settings.default_screen' },
  { section: 'general', title: 'settings.close_to_tray', desc: 'settings.close_to_tray_desc' },
  { section: 'general', title: 'settings.internationalization' },
  { section: 'general', title: 'settings.explore_search_history', desc: 'settings.explore_search_history_desc' },
  { section: 'appearance', title: 'settings.dark_mode' },
  { section: 'appearance', title: 'settings.theme_color' },
  { section: 'appearance', title: 'settings.color_mode' },
  { section: 'now_playing', title: 'settings.cover_style' },
  { section: 'now_playing', title: 'settings.cover_badge', desc: 'settings.cover_badge_desc' },
  { section: 'now_playing', title: 'settings.np_title', desc: 'settings.np_title_desc' },
  { section: 'now_playing', title: 'settings.np_toolbar', desc: 'settings.np_toolbar_desc' },
  { section: 'now_playing', title: 'settings.quality_switch', desc: 'settings.quality_switch_desc' },
  { section: 'background', title: 'settings.background_image' },
  { section: 'background', title: 'settings.bg_blur' },
  { section: 'background', title: 'settings.bg_opacity' },
  { section: 'background', title: 'settings.bg_dim' },
  { section: 'background', title: 'settings.enhanced_advanced_blur', desc: 'settings.enhanced_advanced_blur_desc' },
  { section: 'background', title: 'settings.enhanced_advanced_blur_radius' },
  { section: 'audio', title: 'settings.audio_output', desc: 'settings.audio_output_desc' },
  { section: 'audio', title: 'settings.normalize', desc: 'settings.normalize_desc' },
  { section: 'audio', title: 'settings.volume_balance' },
  { section: 'audio', title: 'settings.multichannel_drc', desc: 'settings.multichannel_drc_desc' },
  { section: 'playback', title: 'settings.fade_in', desc: 'settings.fade_in_desc' },
  { section: 'playback', title: 'settings.fade_in_duration' },
  { section: 'playback', title: 'settings.fade_out_duration' },
  { section: 'playback', title: 'settings.crossfade_next', desc: 'settings.crossfade_next_desc' },
  { section: 'playback', title: 'settings.crossfade_in_duration' },
  { section: 'playback', title: 'settings.crossfade_out_duration' },
  { section: 'playback', title: 'settings.keep_progress', desc: 'settings.keep_progress_desc' },
  { section: 'playback', title: 'settings.remember_long_form_progress', desc: 'settings.remember_long_form_progress_desc' },
  { section: 'playback', title: 'settings.keep_mode', desc: 'settings.keep_mode_desc' },
  { section: 'network', title: 'settings.bypass_proxy', desc: 'settings.bypass_proxy_desc' },
  { section: 'listen_together', title: 'listen_together.server_url' },
  { section: 'listen_together', title: 'listen_together.nickname' },
  { section: 'listen_together', title: 'listen_together.allow_member_control' },
  { section: 'listen_together', title: 'listen_together.auto_pause_on_change' },
  { section: 'listen_together', title: 'listen_together.share_audio_links' },
  { section: 'listen_together', title: 'listen_together.reset_identity', desc: 'listen_together.reset_identity_desc' },
  { section: 'downloads', title: 'settings.go_to_downloads' },
  { section: 'downloads', title: 'settings.download_parallelism', desc: 'settings.download_parallelism_desc' },
  { section: 'downloads', title: 'settings.download_metadata', desc: 'settings.download_metadata_desc' },
  { section: 'downloads', title: 'settings.download_embed_lyrics', desc: 'settings.download_embed_lyrics_desc' },
  { section: 'downloads', title: 'settings.download_follow_playback_quality', desc: 'settings.download_follow_playback_quality_desc' },
  { section: 'downloads', title: 'settings.netease_quality' },
  { section: 'downloads', title: 'settings.youtube_quality' },
  { section: 'downloads', title: 'settings.bili_quality' },
  { section: 'downloads', title: 'settings.download_format' },
  { section: 'downloads', title: 'settings.download_dir', desc: 'settings.download_dir_desc' },
  { section: 'lyrics', title: 'settings.lyric_font_size' },
  { section: 'lyrics', title: 'settings.show_translation', desc: 'settings.show_translation_desc' },
  { section: 'lyrics', title: 'settings.show_romanization', desc: 'settings.show_romanization_desc' },
  { section: 'lyrics', title: 'settings.prefer_word_timed_lyrics', desc: 'settings.prefer_word_timed_lyrics_desc' },
  { section: 'lyrics', title: 'settings.default_lyric_source', desc: 'settings.default_lyric_source_desc' },
  { section: 'lyrics', title: 'settings.lyric_blur', desc: 'settings.lyric_blur_desc' },
  { section: 'lyrics', title: 'settings.blur_strength' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.open', desc: 'desktop_lyrics.open_desc' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.menu_bar', desc: 'desktop_lyrics.menu_bar_desc', keywords: ['macOS', '状态栏', '菜单栏', 'menu bar'], macOnly: true },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.theme' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.layout' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.align' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.karaoke' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.secondary' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.font' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.font_size' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.font_weight' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.letter_spacing' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.secondary_size' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.stroke' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.stroke_width' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.shadow' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.shadow_blur' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.glow' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.opacity' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.background' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.background_opacity' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.show_track_info' },
  { section: 'desktop_lyrics', title: 'desktop_lyrics.reset', desc: 'desktop_lyrics.reset_desc' },
  { section: 'motion', title: 'settings.advanced_lyrics', desc: 'settings.advanced_lyrics_desc' },
  { section: 'motion', title: 'settings.dynamic_bg', desc: 'settings.dynamic_bg_desc' },
  { section: 'motion', title: 'settings.audio_reactive', desc: 'settings.audio_reactive_desc' },
  { section: 'motion', title: 'settings.cover_blur', desc: 'settings.cover_blur_desc' },
  { section: 'motion', title: 'settings.blur_amount' },
  { section: 'motion', title: 'settings.bg_darken' },
  { section: 'playback_sources', title: 'settings.youtube_playback_source', desc: 'settings.youtube_playback_source_desc' },
  { section: 'playback_sources', title: 'settings.netease_local_source_fallback', desc: 'settings.netease_local_source_fallback_desc' },
  { section: 'playback_sources', title: 'settings.netease_auto_source_switch', desc: 'settings.netease_auto_source_switch_desc' },
  { section: 'quality', title: 'settings.netease_quality' },
  { section: 'quality', title: 'settings.youtube_quality' },
  { section: 'quality', title: 'settings.bili_quality' },
  { section: 'storage', title: 'settings.cache_limit' },
  { section: 'storage', title: 'settings.storage_usage_title', desc: 'settings.storage_usage_desc' },
  { section: 'storage', title: 'settings.log_to_file', desc: 'settings.log_to_file_desc' },
  { section: 'storage', title: 'settings.log_level', desc: 'settings.log_level_desc' },
  { section: 'storage', title: 'settings.open_log_dir', desc: 'settings.open_log_dir_desc' },
  { section: 'backup', title: 'settings.sync_frequency', desc: 'settings.sync_frequency_desc' },
  { section: 'backup', title: 'settings.github_sync', desc: 'settings.github_sync_desc' },
  { section: 'backup', title: 'settings.auto_sync', desc: 'settings.auto_sync_desc' },
  { section: 'backup', title: 'settings.sync_now' },
  { section: 'backup', title: 'settings.silent_failures', desc: 'settings.silent_failures_desc' },
  { section: 'backup', title: 'settings.webdav_sync' },
  { section: 'backup', title: 'settings.export_playlist', desc: 'settings.export_playlist_desc' },
  { section: 'backup', title: 'settings.import_playlist', desc: 'settings.import_playlist_desc' },
  { section: 'backup', title: 'settings.export_config', desc: 'settings.export_config_desc' },
  { section: 'backup', title: 'settings.import_config', desc: 'settings.import_config_desc' },
  { section: 'language', title: 'settings.language', desc: 'settings.language_desc' },
  { section: 'about', title: 'settings.build_uuid' },
  { section: 'about', title: 'settings.build_time' },
  { section: 'about', title: 'settings.github', desc: 'settings.github_desc' },
  { section: 'about', title: 'settings.ffmpeg_component' },
  { section: 'now_playing', title: 'settings.audio_bitrate', desc: 'settings.audio_bitrate_desc' },
  { section: 'now_playing', title: 'settings.audio_format', desc: 'settings.audio_format_desc' },
  { section: 'now_playing', title: 'settings.audio_channels', desc: 'settings.audio_channels_desc' },
  { section: 'now_playing', title: 'settings.audio_sample_rate', desc: 'settings.audio_sample_rate_desc' },
  { section: 'now_playing', title: 'settings.audio_bit_depth', desc: 'settings.audio_bit_depth_desc' },
  { section: 'shortcuts', title: 'shortcuts.global_enable', desc: 'shortcuts.global_enable_desc', keywords: ['hotkey', '热键', 'keyboard', '键盘'] },
  ...['toggle_play', 'previous', 'next', 'seek_back', 'seek_forward', 'volume_up', 'volume_down', 'mute', 'shuffle', 'repeat', 'like', 'desktop_lyrics', 'now_playing', 'search', 'show_window']
    .map(id => ({ section: 'shortcuts', title: `shortcuts.${id}`, keywords: ['shortcut', '快捷键'] })),
]
