// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeriPlayer.Data.Database;

#nullable disable

namespace NeriPlayer.Data.Migrations
{
    [DbContext(typeof(NeriDbContext))]
    [Migration("20260817141212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaybackStatsEntity", b =>
                {
                    b.Property<long>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastPlayedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPlayMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId");

                    b.ToTable("playback_stats", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePlatform")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistMemberEntity", b =>
                {
                    b.Property<long>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "Position");

                    b.HasIndex("SongId");

                    b.ToTable("playlist_members", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.SongEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedLyric")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedLyricSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedTranslatedLyric")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubAudioId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserLyricOffsetMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StableKey")
                        .IsUnique();

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.StatBucketEntity", b =>
                {
                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DayKey")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ListenMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId", "DayKey");

                    b.ToTable("stat_buckets", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistMemberEntity", b =>
                {
                    b.HasOne("NeriPlayer.Data.Entities.PlaylistEntity", "Playlist")
                        .WithMany("Members")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeriPlayer.Data.Entities.SongEntity", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
