// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeriPlayer.Data.Database;

#nullable disable

namespace NeriPlayer.Data.Migrations
{
    [DbContext(typeof(NeriDbContext))]
    [Migration("20260827145146_AddSyncTables")]
    partial class AddSyncTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NeriPlayer.Data.Entities.DownloadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StableKey")
                        .IsUnique();

                    b.ToTable("downloads", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.DownloadQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnqueuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StableKey");

                    b.ToTable("download_queue", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.DownloadRecoveryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.ToTable("download_recovery", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.DownloadSnapshotEntity", b =>
                {
                    b.Property<string>("RootKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bucket")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("RootKey", "Bucket", "EntryKey");

                    b.ToTable("download_snapshots", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaybackStatsEntity", b =>
                {
                    b.Property<long>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastPlayedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPlayMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId");

                    b.ToTable("playback_stats", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePlatform")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistMemberEntity", b =>
                {
                    b.Property<long>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "Position");

                    b.HasIndex("SongId");

                    b.ToTable("playlist_members", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.SongEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedLyric")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedLyricSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedTranslatedLyric")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubAudioId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserLyricOffsetMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StableKey")
                        .IsUnique();

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.StatBucketEntity", b =>
                {
                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DayKey")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ListenMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId", "DayKey");

                    b.ToTable("stat_buckets", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.SyncCheckpointEntity", b =>
                {
                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Scope");

                    b.ToTable("sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.SyncMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Revision")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("sync_metadata", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.SyncOutboxEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RefKey");

                    b.ToTable("sync_outbox", (string)null);
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistMemberEntity", b =>
                {
                    b.HasOne("NeriPlayer.Data.Entities.PlaylistEntity", "Playlist")
                        .WithMany("Members")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeriPlayer.Data.Entities.SongEntity", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("NeriPlayer.Data.Entities.PlaylistEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
