<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAvalonia>true</UseAvalonia>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="LibVLCSharp.Avalonia" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeriPlayer.Core\NeriPlayer.Core.csproj" />
    <ProjectReference Include="..\NeriPlayer.Data\NeriPlayer.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeriPlayer.SourceGen\NeriPlayer.SourceGen.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
