using Microsoft.CodeAnalysis;

namespace NeriPlayer.SourceGen;

/// <summary>
/// 设置键常量源生成器（对标 start.md 10.6 / Analysis.md 23.2 @AutoSetting）。
/// 当前生成固定常量集；后续可扩展为按 [Setting] 属性标记的类动态生成。
/// </summary>
[Generator]
public sealed class SettingsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SettingsKeys.g.cs",
@"// <auto-generated />
namespace NeriPlayer.UI.Settings
{
    /// <summary>设置键常量（Source Generator 自动生成，对标 start.md 10.6）。</summary>
    public static class SettingsKeys
    {
        public const string AccentColor    = ""accent_color"";
        public const string Theme          = ""theme"";
        public const string PlayerVolume   = ""player_volume"";
        public const string RepeatMode     = ""repeat_mode"";
        public const string ShuffleEnabled = ""shuffle_enabled"";
        public const string LastSyncTime   = ""last_sync_time"";
        public const string LyricOffset    = ""lyric_offset_ms"";
    }
}
");
        });
    }
}
